// <auto-generated />
namespace ProjetoM17E.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fabio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fabio));
        
        string IMigrationMetadata.Id
        {
            get { return "202303020945572_fabio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
